### ISSUE TITLE
C++ Solutions implementation

### ISSUE THREAD

**Issue by vjancik** [gaylemcd/CtCI-6th-Edition#2]
Hi, Would you be interested in ports of the Solutions to C++? I just bought the book and I am reading through it and porting it to C++ (language I will use for interviews) would be a great exercise for me.

Your intention of hosting it (if it's good) would be an additional motivation so to speak.

**Comment by gaylemcd** [comment]
Yes, definitely. We had this for the 5th edition and would love to add them for the 6th edition.

For your reference:
https://github.com/gaylemcd/ctci
